sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
link_replacements:
  - "LICENSE-exasol-jdbc.txt|https://docs.exasol.com/db/latest/connect_exasol/drivers/jdbc.htm"
excludes:
  - "E-PK-CORE-17: Missing required file: '.github/workflows/ci-build-next-java.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_prepare_original_checksum.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_print_quick_checksum.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_upload_github_release_assets.yml'"
  # Pinned version of link checker as workaround for: https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/127
  - "E-PK-CORE-18: Outdated content: '.github/workflows/broken_links_checker.yml'"