language: java

sudo: required

install:
  - sudo apt-get update
  - sudo apt install luarocks
  - sudo luarocks install luacheck
  - sudo luarocks install luacov
  - sudo luarocks install luacov-coveralls
  - sudo luarocks install LuaUnit
  - sudo luarocks install Mockagne
  - sudo luarocks install lua-cjson
  - sudo luarocks install remotelog

# FIXME: Note that until the Lua VS docker image is released, we can only run up to and excluding integration tests.
script:
  - mvn package

after_success:
  - cd target/luacov-reports
  - luacov-coveralls