@startuml
!include ../clean.skin
participant "Exasol Compiler" as compiler order 10
participant init order 20
participant request_dispatcher order 30
participant rls_adapter order 40

compiler -> init : adapter_call(request : JSON string)
activate init
create rls_adapter
init -> rls_adapter : create
create request_dispatcher
init -> request_dispatcher : create
init -> request_dispatcher : init(rls_adapter)
activate request_dispatcher
request_dispatcher -->> init :this
deactivate request_dispatcher
init --> request_dispatcher : adapter_call(request : JSON stiring)
activate request_dispatcher
alt
    request_dispatcher -> rls_adapter : createVirtualSchema(request)
    activate rls_adapter
else
    request_dispatcher -> rls_adapter : get capabilities(request)
else
    request_dispatcher -> rls_adapter : seq_set_properties.plantuml set properties(request)
else
    request_dispatcher -> rls_adapter : pushdown(request)
else
    request_dispatcher -> rls_adapter : refresh(request)
else
    request_dispatcher -> rls_adapter : drop virtual schema(request)
end
activate rls_adapter
...
rls_adapter -->> request_dispatcher : response
deactivate rls_adapter
request_dispatcher -->> init : response : JSON string
deactivate request_dispatcher
init --> compiler : response : JSON string
deactivate init

@enduml