name: CI Build

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt install luarocks
          sudo luarocks install luacheck
          sudo luarocks install luacov
          sudo luarocks install luacov-coveralls
          sudo luarocks install LuaUnit
          sudo luarocks install Mockagne
          sudo luarocks install lua-cjson
          sudo luarocks install remotelog
      - uses: actions/checkout@v2
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Build with Maven"
        run: |
          mvn verify
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov.report.out
          path: target/luacov-reports/luacov.report.out