name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build with Lua ${{ matrix.lua_version }} using Exasol ${{ matrix.docker_db_version }}
    strategy:
      fail-fast: true
      matrix:
        lua_version: [5.4]
        docker_db_version: ["7.1.23", "8.23.0"]
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.lua_version }}-${{ matrix.docker_db_version }}
      cancel-in-progress: true
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Lua ${{ matrix.lua_version }}
        uses: leafo/gh-actions-lua@v9.1.0
        with:
          luaVersion: ${{ matrix.lua_version }}
      - name: "Install LuaRocks"
        uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.9.2"
      - name: "Install dependencies"
        run: |
          luarocks --local install *.rockspec --deps-only
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
          cache: "maven"
      - name: Enable testcontainer reuse
        run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"
      - name: Run tests and build with Maven
        run: |
          eval $(luarocks path)
          mvn --batch-mode clean verify \
              -Dcom.exasol.dockerdb.image=${{ matrix.docker_db_version }} \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -DtrimStackTrace=false
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov.report.out
          path: target/luacov-reports/luacov.report.out
