name: CI Build

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install Lua"
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: 5.4
      - name: "Install LuaRocks"
        uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.8.0"
      - name: "Install dependencies"
        run: |
          luarocks install --local busted
          luarocks install --local luacheck
          luarocks install --local luacov
          luarocks install --local luacov-coveralls
          luarocks install --local LuaUnit
          luarocks install --local Mockagne
          luarocks install --local lua-cjson
          luarocks install --local remotelog
          luarocks install --local exaerror
          luarocks install --local virtual-schema-common-lua
          luarocks install --local amalg
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Prepare container reuse"
        run: |
          echo 'testcontainers.reuse.enable=true' > "/home/runner/.testcontainers.properties"
      - name: "Build with Maven"
        run: |
          mvn verify -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov.report.out
          path: target/luacov-reports/luacov.report.out