name: CI Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  matrix-build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: "bash"
    permissions:
      contents: read
      checks: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.lua_version }}-${{ matrix.exasol_db_version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        lua_version: [5.4]
        exasol_db_version: ["8.24.0", "7.1.25"]
    env:
      DEFAULT_EXASOL_DB_VERSION: "8.24.0"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Lua ${{ matrix.lua_version }}
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.lua_version }}
      - name: "Install LuaRocks"
        uses: leafo/gh-actions-luarocks@v4
        with:
          luaRocksVersion: "3.11.0"
      - name: "Install dependencies"
        run: |
          luarocks --local install *.rockspec --deps-only

      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: |
            11
            17
          cache: "maven"
      - name: Enable testcontainer reuse
        run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"
      - name: Run tests and build with Maven
        run: |
          mvn --batch-mode clean verify \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -DtrimStackTrace=false \
              -Dcom.exasol.dockerdb.image=${{ matrix.exasol_db_version }}
      - name: Publish Test Report for Exasol ${{ matrix.exasol_db_version }}
        uses: scacap/action-surefire-report@v1
        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: luacov.report.out
          path: target/luacov-reports/luacov.report.out
          if-no-files-found: error

  build:
    needs: matrix-build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build successful"
