name: Release Droid - Prepare Original Checksum
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install Lua"
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: 5.4
      - name: "Install LuaRocks"
        uses: leafo/gh-actions-luarocks@v4
        with:
          luaRocksVersion: "3.11.0"
      - name: "Install dependencies"
        run: |
          luarocks --local install *.rockspec --deps-only

      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: |
            11
            17
          cache: "maven"
      - name: Enable testcontainer reuse
        run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"
      - name: Run tests and build with Maven
        run: mvn --batch-mode clean verify
      - name: Prepare checksum
        run: find target -maxdepth 1 \( -name '*.lua' -o -name '*.sql' \) -exec sha256sum "{}" + > original_checksum
      - name: Upload checksum to the artifactory
        uses: actions/upload-artifact@v4
        with:
          name: original_checksum
          retention-days: 5
          path: original_checksum
