name: Release Droid - Print Quick Checksum

on:
  workflow_dispatch:

jobs:
  build:
    - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    - name: "Install Lua"
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: 5.4
    - name: "Install LuaRocks"
      uses: leafo/gh-actions-luarocks@v4
      with:
        luarocksVersion: "3.8.0"
    - name: "Install dependencies"
      run: |
        luarocks --local install *.rockspec --deps-only
    - name: "Set up JDK"
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: "Build with Maven skipping tests"
      run: |
        eval $(luarocks path)
        mvn clean verify --batch-mode -DskipTests -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Print checksum
        run: echo 'checksum_start==';find target -maxdepth 1 '(' -name "*.lua" -o -name "*.sql" ')' -exec sha256sum "{}" + | xargs;echo '==checksum_end'

