name: Release Droid - Prepare Original Checksum

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt install luarocks
          sudo luarocks install luacheck
          sudo luarocks install luacov
          sudo luarocks install luacov-coveralls
          sudo luarocks install LuaUnit
          sudo luarocks install Mockagne
          sudo luarocks install lua-cjson
          sudo luarocks install remotelog
      - uses: actions/checkout@v2
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Prepare container reuse"
        run: |
          echo 'testcontainers.reuse.enable=true' > "/home/runner/.testcontainers.properties"
      - name: Run tests and build with Maven
        run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify --file pom.xml
      - name: Prepare checksum
        run: find target -maxdepth 1 -name *.jar -exec sha256sum "{}" + > original_checksum
      - name: Upload checksum to the artifactory
        uses: actions/upload-artifact@v2
        with:
          name: original_checksum
          retention-days: 5
          path: original_checksum