name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Assets upload URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          with:
            fetch-depth: 0
      - name: "Install Lua"
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: 5.4
      - name: "Install LuaRocks"
        uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.8.0"
      - name: "Install dependencies"
        run: |
          luarocks --local install *.rockspec --deps-only
      - name: "Set up JDK"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Prepare container reuse"
        run: |
          echo 'testcontainers.reuse.enable=true' > "/home/runner/.testcontainers.properties"
      - name: "Build with Maven"
        run: |
          eval $(luarocks path)
          mvn clean verify --batch-mode -DskipTests -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Generate sha256sum files
        run: find target -maxdepth 1 '(' -name "*.lua" -o -name "*.sql" ')' -exec bash -c 'sha256sum {} > {}.sha256' \;
      - name: Upload Lua assets
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.lua
      - name: Upload SQL assets to the GitHub release draft
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.sql
      - name: Upload sha256sum files
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.sha256
      - name: Upload error-code-report
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/error_code_report.json