name: Release Droid - Print Quick Checksum

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Install Lua"
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: 5.4
      - name: "Install LuaRocks"
        uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.9.2"
      - name: "Install dependencies"
        run: |
          luarocks --local install *.rockspec --deps-only
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
          cache: "maven"
      - name: Build with Maven skipping tests
        run: mvn --batch-mode clean verify -DskipTests
      - name: "Print checksum"
        run: echo 'checksum_start==';find target -maxdepth 1 \( -name '*.lua' -o -name '*.sql' \) -exec sha256sum "{}" + | xargs;echo '==checksum_end'
